# Generated by Django 4.2 on 2025-01-28 16:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=125, verbose_name='Brand:')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=125, verbose_name='Category:')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=125, verbose_name='Product:')),
                ('description', models.TextField(verbose_name='Description:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price:')),
                ('characteristcs', models.TextField(blank=True, null=True, verbose_name='Characteristircs:')),
                ('available', models.BooleanField(default=True, verbose_name='Available:')),
                ('main_image', models.ImageField(help_text='En glavni suwret qoyin tovarga:', upload_to='static/images/products/')),
                ('image2', models.ImageField(blank=True, help_text='Bul ekinshi suwret:', null=True, upload_to='static/images/products/')),
                ('image3', models.ImageField(blank=True, help_text='Bul ushinshi suwret:', null=True, upload_to='static/images/products/')),
                ('image4', models.ImageField(blank=True, help_text='Bul tortinshi suwret:', null=True, upload_to='static/images/products/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/images/reviews/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='media/images/reviews/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='media/images/reviews/')),
                ('starts', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (Stars):')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
